---

- name: Set ownership for VirtioFS source directory
  file:
    path: "{{ virtiofs_mount_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0770'
    recurse: yes
