---

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp.gpg
    state: present

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    filename: hashicorp
    state: present

- name: Install Terraform
  apt:
    name: terraform
    state: present
    update_cache: yes

- name: Verify Terraform installation
  command: terraform version
  register: tf_version
  changed_when: false
