---

- name: Install SS clinent & privoxy.
  apt:
    name:
      - shadowsocks-libev
      - Privoxy
    state: present
  when: 
    - ansible_facts['os_family'] == 'Debian'
    - common_proxy | bool

- name: Configure SS connection.
  template:
    src: ss_config.j2
    dest: /etc/shadowsocks-libev/config.json
  notify: restart ss
  when: common_proxy | bool

- name: Configure privoxy.
  blockinfile:
    path: /etc/shadowsocks-libev/config.json
    marker: "# {mark} ANSIBLE GENERATED CONFIG BLOCK"
    block: "{{ lookup('template', 'privoxy_config.j2') }}"
  notify: restart restart privoxy
  when: common_proxy | bool

- name: Add proxy to environment.
  blockinfile:
    path: /etc/environment
    marker: "# {mark} ANSIBLE GENERATED PROXY BLOCK"
    block: "{{ lookup('template', 'enviroment.j2') }}"
  when: common_proxy | bool
