---
# Configure UFW firewall when explicitly enabled.

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Default deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Default allow outgoing
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow needed TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports_tcp }}"

- name: Allow needed UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ ufw_allowed_ports_udp }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
