---
# Configure UFW firewall when explicitly enabled.

- name: Install UFW
  apt:
    name: ufw
    state: present
  when: 
    - common_firewall_enabled | bool
    - ansible_facts['os_family'] == 'Debian'

- name: Default deny incoming
  ufw:
    direction: incoming
    policy: deny
  when: 
    - common_firewall_enabled | bool
    - ansible_facts['os_family'] == 'Debian'

- name: Default allow outgoing
  ufw:
    direction: outgoing
    policy: allow
  when: 
    - common_firewall_enabled | bool
    - ansible_facts['os_family'] == 'Debian'

- name: Allow needed ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_allowed_ports }}"
  when: 
    - common_firewall_enabled | bool
    - ansible_facts['os_family'] == 'Debian'

- name: Enable UFW
  ufw:
    state: enabled
  when: 
    - common_firewall_enabled | bool
    - ansible_facts['os_family'] == 'Debian'
