---
# Apply configuration to all sandbox servers.

- name: Setup sandbox servers
  hosts: sandbox
  become: true

  roles:
    - { role: base_server, tags: ['base_vm'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: docker, tags: ['docker'] }
