---
# Handlers for operations_sever role.

- name: restart ss
  service:
    name: shadowsocks-libev
    state: restarted
    enabled: true

- name: restart privoxy
  service:
    name: privoxy
    state: restarted
    enabled: true

- name: start kubelet
  systemd:
    name: kubelet
    state: start
    enabled: yes
