---
- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Update apt package index after adding Docker repo
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
  when: ansible_facts['os_family'] == 'Debian'
  notify: start docker
